import re, os

loc_path = r"c:\Users\radit\Project\VisualStudioProject\Personal\HOI4MODS\Indonesia Sub Mod 56\HOI4mod\IndonesiaRayaR56\localisation\english\DEI_indonesia_l_english.yml"
with open(loc_path, "r", encoding="utf-8-sig") as f:
    content = f.read()

translations = {
    "INS_royal_scientific_cooperation": "Scientific and Technological Cooperation",
    "INS_the_royal_batavian_society": "Academy of Sciences and Research",
    "INS_institut_teknologi_bandung": "Bandung Institute of Technology (ITB)",
    "dei_focus_f_kitab_kutaramanawa": "Codification of Kutaramanawa Law",
    "dei_focus_f_dharmaputra": "Formation of the Dharmaputra Regiment",
    "dei_focus_f_jung_raksasa": "Grand Ocean Jung Fleet of Majapahit",
    "dei_focus_f_penobatan_maharaja": "Coronation of the Supreme Maharaja",
    "dei_focus_e_baitul_mal": "Central Baitul Mal Treasury",
    "dei_focus_e_mahkamah_syariah": "Supreme Sharia Court",
    "dei_focus_e_akademi_mujahidin": "Mujahidin Military Academy",
    "dei_focus_e_hapus_riba": "Interest-Free Islamic Financial System",
    "dei_focus_e_liga_muslim": "World Muslim Solidarity League",
    "dei_focus_f_sumpah_palapa_baru": "Fulfillment of the New Sumpah Palapa",
    "dei_focus_f_restorasi_trowulan": "Restoration of the Sacred Capital Trowulan",
    "dei_focus_a_pancasila": "Sovereignty of the Pancasila Philosophy",
    "dei_focus_b_angkatan_federal": "Federal Armed Forces",
    "dei_focus_c_komune_tani": "Agrarian Commune Collectivization",
    "dei_focus_c_sita_aset_asing": "Nationalization of Imperial Assets",
    "dei_focus_c_angkatan_kelima": "Formation of the Fifth Army",
    "dei_focus_c_pakta_asia_merah": "Asian Anti-Imperialist Axis",
    "dei_focus_c_pembangunan_semesta": "Universal Planned Development",
    "dei_focus_d_dewan_revolusi": "Supreme Military Revolutionary Council",
    "dei_focus_d_karyawan_abri": "Dwifungsi ABRI Doctrine",
    "dei_focus_d_benteng_samudra": "Nusantara Ocean Fortress",
    "dei_focus_d_komando_selat": "Strategic Strait of Malacca Command",
    "dei_focus_d_hegemoni_selatan": "Indian Ocean Hegemony",
    "dei_idea_guerrilla_doctrine": "Doctrine of Regional Guerrilla Warfare",
    "dei_idea_sishanrata_active": "People's Universal Defense System",
    "trait_dei_sudirman": "Father of TNI & Guerrilla Maestro",
    "trait_dei_urip": "Architect of Armed Forces",
    "trait_dei_yos_sudarso": "Maritime Tiger of the Archipelago",
    "dei_decision_doktrin_gerilya_wilayah": "Regional Warfare & Universal Guerrilla Doctrine",
    "dei_decision_doktrin_gerilya_laut": "Shallow Water & Maritime Guerrilla Doctrine",
    "dei_decision_doktrin_dirgantara_taktis": "Tactical Air Superiority of the Equator",
    "dei_decision_riset_mekanisasi_braat": "Development of Braat Light Tanks",
    "dei_decision_commission_armada_kri": "Modernization & Commissioning of KRI War Fleet",
    "dei_idea_doktrin_gerilya_laut": "Shallow Water Guerrilla Doctrine",
    "INS_infantry_equipment_2": "Pindad Guerrilla Rifle",
    "INS_motorized_equipment_1": "Braat Military Transport Truck",
    "dei_proclaim_khilafah": "Proclaim the Khilafah Islamiyah Nusantara",
    "dei_mechanic_sishanrata": "Proclaim the People's Universal Defense System (Sishanrata)",
    "dei_path_a.11.d": "Before hundreds of thousands gathered in the grand square of Yogyakarta, the President steps up to the rostrum. In a thunderous speech, he issues the Tri Komando Rakyat: thwart the establishment of a puppet colonial state, raise the Sang Saka Merah Putih in West Irian, and prepare total mobilization to defend national independence.",
    "dei_path_a.12.a": "Return to the 1945 Constitution!",
    "dei_path_a.13.d": "Facing perceived neo-colonial encircling maneuvers on the northern frontier, the Republic issues the Dwi Komando Rakyat (Dwikora). Volunteers and commandos prepare along the maritime straits, determined to safeguard revolutionary sovereignty against imperialist encroachment.",
    "dei_path_c.9.d": "Red banners wave over rice paddies and rubber estates as thousands of peasant families join together in socialist agrarian communes (Komune Tani). Landlord estates have been expropriated and redistributed to those who cultivate the soil.",
    "dei_path_c.9.a": "Land to the tiller! Workers and Peasants Live!",
    "dei_path_c.11.d": "Crates of rifles, submachine guns, and field radios are distributed to worker and peasant militias in industrial suburbs and rural villages. The newly inaugurated Fifth Army stands ready to defend the revolution with blood and iron.",
    "dei_path_c.13.t": "The Red Asian Anti-Imperialist Treaty",
    "dei_path_d.10.t": "Implementation of Dwifungsi ABRI",
    "dei_path_d.10.d": "Senior army, navy, and air force commanders are officially appointed as ministers, governors, and directors of state industrial monopolies. The Dwifungsi doctrine binds national development and martial command into an inseparable whole.",
    "dei_path_e.5.t": "Alliance with the Muslim World",
    "dei_path_e.8.d": "A grand congress in Batavia welcomes Muslim leaders from across Malaya, Borneo, and Mindanao.",
    "dei_path_e.11.t": "First Graduates of the Mujahidin Academy",
    "dei_path_e.11.d": "Cadets dressed in green uniforms with silver crescent insignias take their solemn oath of jihad and loyalty to the state. These Mujahidin commanders combine battlefield tacticians with deep religious scholarship.",
    "dei_path_e.12.t": "Abolition of Riba and Islamic Banking",
    "dei_path_e.13.d": "Envoys from Egypt, Syria, Yemen, Pakistan, and Malaya gather in Java to inaugurate the World Muslim Solidarity League. Pledges of mutual defense and religious cooperation echo across the hall.",
    "dei_path_e.14.t": "Proclamation of Khilafah Nusantara",
    "dei_path_e.14.d": "In a solemn ceremony accompanied by prayers and traditional gamelan hymns in the great mosque, the Amir is consecrated as the spiritual and temporal guardian of Khilafah Islamiyah Nusantara. Green flags fly across every province.",
    "dei_path_f.10.t": "The Sacred Renewal of Sumpah Palapa",
    "dei_path_f.10.d": "Standing upon the ancient stone podium before a massive crowd of imperial subjects, the court chamberlain reads the sacred Sumpah Palapa. The nation swears never to rest until all archipelagic lands and seas are unified under one throne.",
    "dei_path_f.13.t": "Launch of the Imperial Jung Warships",
    "dei_path_f.14.t": "Promulgation of Kutaramanawa Dharmasastra",
    "dei_path_f.14.d": "Royal judges read the ancient eighteen chapters of Kutaramanawa law in court. Unjust corruption, banditry, and disloyalty are met with swift imperial justice, restoring harmony (kertaraharja) throughout the realm.",
    "dei_path_f.15.t": "The Coronation of the Supreme Maharaja",
    "dei_path_f.15.d": "Trumpets, gongs, and sacred gamelan fanfare resound through the great throne hall of Trowulan. Crowned with the golden Makuta under the radiant Surya Majapahit emblem, the Maharaja is proclaimed Emperor of All Nusantara.",
    "dei_path_f.15.a": "Long Live Majapahit! Long Live the Maharaja!",
    "dei_leadership.6.t": "Grand Ceremony at the Trowulan Palace",
    "dei_leadership.6.d": "Amid fragrant sandalwood incense and the echoing chimes of heirloom gamelan, hereditary princes, royal courtiers, and Dharmaputra knights assemble at the restored sanctuary of Trowulan. They seek to anoint the supreme ruler of Nusantara: consecrated descendant Sri Maharaja Suryawikrama, revered reformist monarch Sri Sultan Hamengkubuwono IX, or senior aristocratic regent K.R.M.T. Wuryaningrat.",
    "dei_leadership.6.a": "Sri Maharaja Suryawikrama - Divine Sovereign of Wilwatikta!",
    "dei_leadership.5.d": "Eminent ulama, mujahidin commanders, and Islamic scholars assemble in Tasikmalaya to establish an Islamic polity (Daulah Islamiyah). Delegates deliberate over supreme leadership: unyielding Imam Sekarmaji Marijan Kartosuwiryo, visionary democratic statesman Mohammad Natsir, or esteemed traditionalist cleric K.H. Wahid Hasyim.",
    "dei_leadership.3.d": "Under the crimson banners of the Hammer and Sickle, delegates from the PKI, peasant unions, and red militia battalions convene in Madiun. A decisive choice must be made between the orthodox Comintern line of Musso, the radical sovereign mass-action doctrine of Tan Malaka, and the socialist intellectual leadership of Amir Sjarifuddin.",
    "dei_leadership.3.b": "Tan Malaka - Supreme Comrade of the Murba Revolution!",
    "dei_idea_agrarian_communes": "Agrarian Commune Collective",
    "dei_idea_karyawan_abri": "Dwifungsi ABRI Administration",
    "dei_idea_mujahidin_spirit": "Mujahidin Officer Cadre",
    "dei_idea_palapa_oath": "Sumpah Palapa Vow",
    "dei_idea_kutaramanawa_law": "Kutaramanawa Justice",
    "INS_democratic_party_long": "National Democratic Party",
    "INS_communism_party_long": "Communist Party of Indonesia",
    "INS_fascism_party": "Revolutionary Council",
    "INS_fascism_party_long": "Supreme Revolutionary Leadership Council",
    "INS_islamist_party_long": "Council of Imams & Majlis Shuro NII",
    "INS_REPUBLIK_NKRI_party_long": "National Democratic Party",
    "INS_REPUBLIK_SOSIALIS_party_long": "Socialist Party of Indonesia",
    "INS_KOMUNIS_RRI": "People's Republic of Indonesia",
    "INS_KOMUNIS_RRI_party_long": "Communist Party of Indonesia",
    "INS_KOMUNIS_SOVIET_party_long": "Communist Party of Indonesia - Comintern Section",
    "INS_KOMUNIS_FRONT": "Nusantara People's Democratic Front",
    "INS_KOMUNIS_FRONT_party_long": "People's Democratic Front",
    "INS_OTORITER_NKRI_party": "Revolutionary Council",
    "INS_OTORITER_NKRI_party_long": "Supreme Revolutionary Leadership Council",
    "INS_OTORITER_JUNTA": "Indonesian Revolutionary Military Command",
    "INS_OTORITER_JUNTA_party_long": "Presidium of the Military Revolutionary HQ",
    "INS_OTORITER_RAYA": "Indonesian Great Military Empire",
    "INS_ISLAMIS_KHILAFAH": "Khilafah Islamiyah Nusantara",
    "INS_ISLAMIS_KHILAFAH_party_long": "Council of Khilafah Islamiyah Nusantara",
    "INS_MAJAPAHIT_SURYA_party_long": "Council of the Seven Princes of Surya Wilwatikta",
    "INS_MAJAPAHIT_NUSANTARA_party_long": "Council of the Grand Ministers of Nusantara Raya",
    "INS_ESCORT_REPUBLIK": "KRI: Strait Patrol & Transport Fleet",
    "INS_ESCORT_KOMUNIS": "People's Patrol & Logistics Fleet",
    "INS_CAPITAL_SHIPS_OTORITER": "KRI: Revolutionary Council Battlefleet",
    "INS_ESCORT_OTORITER": "KRI: Ocean Frontline Escort",
    "INS_CAPITAL_SHIPS_ISLAMIS": "Mujahidin Battlefleet & Tauhid Fortress",
    "INS_CAPITAL_SHIPS_MAJAPAHIT": "Wilwatikta Sea Jung Battlefleet",
    "INS_DESTROYERS_MAJAPAHIT": "Jung Warship & Jalayanapati Escort Fleet",
    "INS_SUBMARINES_MAJAPAHIT": "Sea Treasure Submarine Fleet",
    "INS_ESCORT_MAJAPAHIT": "Jung Sail & Ceremony Trade Fleet",
    "DEI_OTORITER": "Revolutionary Council Guard Regiment & Bela Negara Pioneers",
    "INS_koninklijk_nederlands_indisch_leger": "Armed Forces Modernization",
    "INS_the_flying_dutchmen": "Nusantara Paratrooper Regiment",
    "INS_ambonese_auxilaries": "Nusantara Regional Militia Regiment",
    "DEI_KOMANDO": "Commando Regiment & Guerrilla Forces",
    "DEI_KAVALERI": "Nusantara Cavalry & Armored Regiment",
    "DEI_maharaja_suryawikrama": "Sri Maharaja Suryawikrama",
    "DEI_tan_malaka": "Tan Malaka",
    "trait_dei_sukarno": "Bung Karno - Voice of the People",
    "trait_dei_tan_malaka": "Father of the Republic & Murba Guerrilla",
    "trait_dei_soeharto_leader": "General of Development & Order",
    "trait_dei_simatupang": "Chief of Naval Staff",
    "trait_dei_john_lie": "Tiger of the Strait of Malacca",
}

pattern = re.compile(r'^(\s*)([a-zA-Z0-9_\.]+):\d*\s*"(.*)"', re.MULTILINE)
matches = pattern.findall(content)
count = 0
for match in matches:
    indent, key, val = match
    if key in translations:
        content = content.replace(
            f'{indent}{key}: "{val}"',
            f'{indent}{key}: "{translations[key]}"',
            1
        )
        count += 1

with open(loc_path, "w", encoding="utf-8") as f:
    f.write('\xef\xbb\xbf' + content)

print(f"Translated {count} Indonesian titles to English. File saved with UTF-8 BOM.")
